# Generated by Django 4.0.3 on 2022-04-24 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=255)),
                ('empleados', models.IntegerField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('codigo', models.TextField()),
                ('almacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='almacen_nombre', to='almacen_app.almacen')),
            ],
        ),
    ]
